fix: update readme(s)
linz/topo-imagery pull request #11
Opened 2022-06-13 03:00 UTC by MDavidson17

- Overall repo readme.md updated to include information about the topo-imagery package. 
- readme.md in container folder deleted to reduce the risk of forgetting to update one or the other.

**Reasoning:**
https://docs.github.com/en/packages/learn-github-packages/publishing-a-package#about-published-packages

> "A repository can be connected to more than one package. To prevent confusion, make sure the README and description clearly provide information about each package."

2022-06-13 03:05 UTC, amfage approved these changes

2022-06-13 21:46 UTC, paulfouquet requested changes
As per our discussion earlier during standup, we might only have one container in this repo. I've got a couple of suggestions around that.

2022-06-13 21:46 UTC, paulfouquet commented on README.md
> +# Packages
As we have only one package for now (and probably want only one for this repository for simplicity), we won't have a list of different containers.
What do you think of removing the `s` of `Packages` and not having a list?

2022-06-13 21:46 UTC, paulfouquet commented on README.md
> +### GDAL Container
Same here, should we rename this title as `Container description` or something like that?

2022-06-14 04:25 UTC, paulfouquet requested changes
I would suggest to use the type `docs` instead of `fix` for this PR
> docs: Documentation only changes

[*source](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type)

2022-06-14 04:33 UTC, MDavidson17 commented
> I would suggest to use the type `docs` instead of `fix` for this PR
> 
> > docs: Documentation only changes
> 
> [*source](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type) [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary)

good point, very true :+1:

2022-06-16 04:03 UTC, paulfouquet approved these changes

2022-06-16 04:23 UTC, amfage approved these changes

2022-06-16 20:16 UTC, merged