Feat: create stac items TDE-452
linz/topo-imagery pull request #133
Opened 2022-09-09 03:46 UTC by MDavidson17

superceeds the already reviewed: https://github.com/linz/topo-imagery/pull/100

2022-09-18 23:09 UTC, paulfouquet commented on scripts/stac/imagery/item.py
> +    def update_spatail(self, geometry: List[List[float]], bbox: List[float]) -> None:
typo here `spatail` -> `spatial`

2022-09-18 23:13 UTC, paulfouquet commented on scripts/stac/imagery/item.py
> +    def add_collection(self, title: str, path: str) -> None:
You could pass the `collection` object and manage getting the needed information from it in here

2022-09-18 23:21 UTC, paulfouquet commented on scripts/stac/tests/item_test.py
> +def test_imagery_stac_item(mocker) -> None:  # type: ignore
Should we add adding a collection to the item in this test?

2022-09-18 23:22 UTC, paulfouquet requested changes
a couple of comments

2022-09-22 23:25 UTC, amfage approved these changes

2022-09-22 23:33 UTC, amfage approved these changes

2022-09-22 23:51 UTC, amfage approved these changes

2022-09-22 23:51 UTC, amfage commented on scripts/stac/imagery/collection.py
```suggestion


```

2022-09-22 23:55 UTC, amfage approved these changes

2022-09-23 00:00 UTC, merged