feat: refactor create collection TDE-528
linz/topo-imagery pull request #205
Opened 2022-11-08 01:19 UTC by MDavidson17

partial completed of TDE-528 (still need to update workflow)

the script has been altered to:
- create multiple collections during standardise_validate
- flatten_collection.py has been created to take a list of collections (from aws-list) and merge them if they have the same collection_id

2022-11-08 21:55 UTC, paulfouquet requested changes
Looks good to me. Only a couple of minor comments and would be nice to have few unit tests for the merging functions.

2022-11-08 21:55 UTC, paulfouquet commented on scripts/flatten_collections.py
> +import argparse
Would `merge_collections.py` make more sense for this script?

2022-11-08 21:55 UTC, paulfouquet commented on scripts/flatten_collections.py
> +        # merge links
Would be nice put these 3 following merge into separates function and have some unit tests for them, simulating a list of `partial_stac` to be merged together.

2022-11-08 21:55 UTC, paulfouquet commented on scripts/flatten_collections.py
> +
code style: few blank lines that I don't think are necessary. Blank lines should be used to indicate logical sections.

2022-11-14 21:59 UTC, amfage approved these changes
:+1:

2022-11-14 22:00 UTC, paulfouquet requested changes

2022-11-14 22:03 UTC, MDavidson17 commented on scripts/conftest.py
> +@pytest.fixture(autouse=True)
Yea, I tried this first but got mypy issues but I'll take a closer look

2022-11-16 03:06 UTC, MDavidson17 commented
superceeded by: `https://github.com/linz/topo-imagery/pull/219`

2022-11-16 03:06 UTC, closed without merging