fix: TDE-454 remove `standardise` from file name
linz/topo-imagery pull request #92
Opened 2022-08-15 22:40 UTC by MDavidson17

2022-08-18 21:24 UTC, paulfouquet requested changes

2022-08-18 21:24 UTC, paulfouquet commented on scripts/standardising.py
> +    standardized_file_name = f"{get_file_name_from_path(s3_path.key)}"
You don't need to format the string (`f" "`) as `get_file_name_from_path()` returns a string

2022-08-24 01:07 UTC, blacha approved these changes

2022-08-24 02:36 UTC, paulfouquet approved these changes

2022-08-24 21:04 UTC, amfage approved these changes

2022-08-24 21:04 UTC, merged